### ISSUE TITLE
Multiple instances of plugin run on consecutive button clicks

### ISSUE THREAD

**Issue by Panopto** [Panopto/Panopto-Button-for-Atto#1]
After inserting a video via the Panopto button once, if you click the button a second time without refreshing the page and insert more content, this content will be inserted twice. If you then click the button a third time and insert more content, this content will be inserted three times, etc. This seems to be due to the fact that while clicking the panopto button on the editor toolbar opens a new instance of the plugin, closing the plugin window does not terminate it's plugin instance but simply hides it, meaning that consecutive button presses open multiple instances of the plugin that all receive the same input commands. From the Atto API, I cannot figure out a way to terminate the plugin instance on closure rather than hiding it.

**Comment by panoptorelease** [comment]
Fixed by e9f1e1b4e74faafc39a2c20a769f3c42ac030205
