### ISSUE TITLE
Error since last update of Panopto

### ISSUE THREAD

**Issue by Richardvi** [Panopto/Panopto-Button-for-Atto#13]
We have been updated to Panopto 6 and the Panopto button for Atto stopped working. Now we get this error:
-------

**Not Found**
The requested URL /Panopto/Pages/Sessions/EmbeddedUpload.aspx was not found on this server.

Additionally, a 404 Not Found error was encountered while trying to use an ErrorDocument to handle the request.

------

Can someone verify if the Panopto-Atto button still works with the latest version of Panopto?

**Comment by pennedav** [comment]
I'm experiencing this issue as well. I don't think it has to do with Panopto 6, however. It appears to be browser related. In Chrome we have this problem, but in Safari and Firefox it works. For some reason when the user clicks the button, it tries to load the /Panopto/Pages/Sessions/EmbeddedUpload.aspx path from our local server, then falls back to loading that path from our Panopto instance hostname. I'm not sure why it tries to load from local first. This happens on both Chrome and FF but in Chrome the second request is getting blocked. Maybe a Chrome update that adds some security feature is getting triggered that FF and Safari don't have?

**Comment by jmalmsten-panopto** [comment]
Hi,

I believe this issue may have been fixed with the most recent Panopto beta release 2019012900. If this issue persists please open a support ticket with Panopto.

Thanks,
Joe

**Comment by Richardvi** [comment]
It's not fixed and a support ticket was opened.

**Comment by pennedav** [comment]
Release 2019012900 fixed the problem for me.
