### ISSUE TITLE
URL not found error

### ISSUE THREAD

**Issue by haietza** [Panopto/Panopto-Button-for-Atto#15]
When a user first goes to edit a page and clicks the Panopto button in the Atto editor, the iframe displays this error initially: Not Found
The requested URL /Panopto/Pages/Sessions/EmbeddedUpload.aspx was not found on this server.

Sometimes clicking out and trying again successfully connects the user to their media list in the Panopto iframe, sometimes it does not. It appears that it will eventually work on Mac Chrome but will never work on Windows Chrome. It does work on Windows Firefox.

We are using version 2018011800 of the plugin.

It does not appear to occur with the TinyMCE plugin.

**Comment by jmalmsten-panopto** [comment]
Hi,

2019012900 should fix this issue, if this issue still persists please open a support ticket with Panopto.

Thanks,
Joe
