### ISSUE TITLE
Auto sync of users on button load

### ISSUE THREAD

**Issue by neeesn** [Panopto/Panopto-Button-for-Atto#17]
Hi - We have a problem.
The button seems to be calling and syncing through soap each time the editor is loaded, and its slowing the site.  Esp. on a quiz, with multiple questions where the editor is loaded several times.
Can it be an option in the settings to Sync the user? -is it nessesary to call the SyncExternalUser? Or is there some settings we have overlooked.

We run a profile to see the loade times - it attached to this issue
![Profilerun - callgraph](https://user-images.githubusercontent.com/1931926/63834335-65ee8d80-c975-11e9-8493-caa32a55cfcd.png)

**Comment by jmalmsten-panopto** [comment]
Hi,

We are going to look into this issue in the near future. 
If this call is giving too many issues before then you may comment out the SyncExternalUser call from the Atto button and it should still work.

The line to comment out is located here:
https://github.com/Panopto/Panopto-Button-for-Atto/blob/master/lib.php#L62

comment out lines 62-68 and the sync call should no longer happen. 

If you need any other assistance until then please open or update your current support ticket with Panopto.

Thanks,
Joe
