### ISSUE TITLE
Panopto button causing slowness

### ISSUE THREAD

**Issue by sleitao** [Panopto/Panopto-Button-for-Atto#21]
We are experiencing exactly the same issue as #17 

I commented lines 62-68 as recommended because some users were complaining about moodle running slow... 
Some pages (quiz with multiple questions) were taking almost 10 seconds loading, and after removing the sync, loading was reduced to 1 second. 

However I feel a little uncomfortable and not confidante removing that piece of code because it seems that this issue was raised 2 years ago, marked as closed, and SyncExternalUser call is still on stable code...  Could you please give me a little more confidence :) and assure me this is the best/only way to solve this issue?

Thank you!

**Comment by jmalmsten-panopto** [comment]
Hi,

Thank you for your patience. The sync was removed in the latest release of the Panopto button for Atto. Please update to the latest version and you should no longer experience this issue. 

Thanks,
Joe Malmsten
